//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMetroUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANG_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIANG_VIEN()
        {
            this.GV_MH = new HashSet<GV_MH>();
            this.LUONGTHANG_GV = new HashSet<LUONGTHANG_GV>();
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
            this.TINHLUONGs = new HashSet<TINHLUONG>();
        }
    
        public int IDGV { get; set; }
        public string MAGV { get; set; }
        public string TENGV { get; set; }
        public string MAHV { get; set; }
        public string MACV { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string QUEQUAN { get; set; }
        public string DIACHITAMCHU { get; set; }
        public string EMAIL { get; set; }
        public bool GIOITINHGV { get; set; }
        public string SDTNGUOITHANGV { get; set; }
        public string CMND { get; set; }
        public string TRANGTHAIGV { get; set; }
        public string MAKHOA { get; set; }
    
        public virtual CHUC_VU CHUC_VU { get; set; }
        public virtual KHOA KHOA { get; set; }
        public virtual HOC_VI HOC_VI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_MH> GV_MH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONGTHANG_GV> LUONGTHANG_GV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINHLUONG> TINHLUONGs { get; set; }
    }
}
