//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMetroUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONGTHANG_GV
    {
        public int IDGV { get; set; }
        public string MATHANG { get; set; }
        public string NAMGVTHUCHIEN { get; set; }
        public Nullable<decimal> LUONGTONG { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        public virtual THANGLUONG THANGLUONG { get; set; }
    }
}
