//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMetroUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON_HOC()
        {
            this.GV_MH = new HashSet<GV_MH>();
            this.NH_MH = new HashSet<NH_MH>();
            this.SV_MH = new HashSet<SV_MH>();
            this.THOIKHOABIEUx = new HashSet<THOIKHOABIEU>();
            this.TINHLUONGs = new HashSet<TINHLUONG>();
        }
    
        public int IDMH { get; set; }
        public string MAMH { get; set; }
        public string TENMH { get; set; }
        public string MOTA { get; set; }
        public string NOIDUNG { get; set; }
        public string YEUCAUMH { get; set; }
        public string MALMH { get; set; }
        public string TRANGTHAIMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_MH> GV_MH { get; set; }
        public virtual LOAI_MH LOAI_MH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NH_MH> NH_MH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SV_MH> SV_MH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINHLUONG> TINHLUONGs { get; set; }
    }
}
