//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMetroUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANHOI_YKIEN
    {
        public int IDPH { get; set; }
        public string MAPH { get; set; }
        public string TENPH { get; set; }
        public string NOIDUNGPH { get; set; }
        public string NGUOIPH { get; set; }
        public string NGUOITLPH { get; set; }
        public Nullable<System.DateTime> NGAYGIONEUPH { get; set; }
        public Nullable<System.DateTime> NGAYGIOTLPH { get; set; }
        public string TRANGTHAIPH { get; set; }
    }
}
