//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMetroUI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHOCVUEntities : DbContext
    {
        public QLHOCVUEntities()
            : base("name=QLHOCVUEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CA_HOC> CA_HOC { get; set; }
        public virtual DbSet<CHUC_VU> CHUC_VU { get; set; }
        public virtual DbSet<GIANG_VIEN> GIANG_VIEN { get; set; }
        public virtual DbSet<GV_MH> GV_MH { get; set; }
        public virtual DbSet<HOC_KY> HOC_KY { get; set; }
        public virtual DbSet<HOC_VI> HOC_VI { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<KHOA_HOC> KHOA_HOC { get; set; }
        public virtual DbSet<LOAI_MH> LOAI_MH { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<LUONGTHANG_GV> LUONGTHANG_GV { get; set; }
        public virtual DbSet<MON_HOC> MON_HOC { get; set; }
        public virtual DbSet<NAM> NAMs { get; set; }
        public virtual DbSet<NGANH_HOC> NGANH_HOC { get; set; }
        public virtual DbSet<NH_MH> NH_MH { get; set; }
        public virtual DbSet<PHANHOI_YKIEN> PHANHOI_YKIEN { get; set; }
        public virtual DbSet<PHONG_HOC> PHONG_HOC { get; set; }
        public virtual DbSet<QUYDOITIEN> QUYDOITIENs { get; set; }
        public virtual DbSet<SINH_VIEN> SINH_VIEN { get; set; }
        public virtual DbSet<SV_MH> SV_MH { get; set; }
        public virtual DbSet<THANGLUONG> THANGLUONGs { get; set; }
        public virtual DbSet<THOIKHOABIEU> THOIKHOABIEUx { get; set; }
        public virtual DbSet<TINHLUONG> TINHLUONGs { get; set; }
    }
}
