//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMetroUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINH_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINH_VIEN()
        {
            this.SV_MH = new HashSet<SV_MH>();
        }
    
        public int IDSV { get; set; }
        public string MASV { get; set; }
        public string TENSV { get; set; }
        public string CMND { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string QUEQUANSV { get; set; }
        public Nullable<double> DIEMSV { get; set; }
        public string SVKHOAHOC { get; set; }
        public string DIACHITHUONGCHU { get; set; }
        public string SDT { get; set; }
        public bool GIOITINH { get; set; }
        public string SDTNGUOITHANSV { get; set; }
        public string EMAIL { get; set; }
        public int IDLOP { get; set; }
    
        public virtual LOP LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SV_MH> SV_MH { get; set; }
    }
}
