//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMetroUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANGLUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANGLUONG()
        {
            this.LUONGTHANG_GV = new HashSet<LUONGTHANG_GV>();
        }
    
        public string MATHANG { get; set; }
        public string TENTHANG { get; set; }
        public Nullable<int> SOTIETTOIDA { get; set; }
        public int SOTIETTOITHIEU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUONGTHANG_GV> LUONGTHANG_GV { get; set; }
    }
}
